import 'package:flutter/material.dart';

/* UndefinedNode Group 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup5Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
