import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Rectangle image 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 0.99,
            b: 0.11,
            c: -0.11,
            d: 0.99,
            child: Container(
              width: 90.0906982421875,
              height: 90.0906982421875,
            )));
  }
}
