import 'package:flutter/material.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedFINDTOILETWidget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedTOILETHUNTWidget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax1widget/generated/GeneratedWelcomebackbuddyWidget.dart';

/* Frame iPhone 14 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(142, 230, 162, 255),
                              ),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 64.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 283.0,
                              height: 73.0,
                              child: GeneratedWelcomebackbuddyWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 435.0,
                              height: 155.0,
                              child: GeneratedTOILETHUNTWidget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 679.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 64.0,
                              child: GeneratedGroup1Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 727.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 21.0,
                              child: GeneratedFINDTOILETWidget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 765.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 64.0,
                              child: GeneratedGroup2Widget(),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 215.0,
                              right: null,
                              bottom: null,
                              width: 437.6410217285156,
                              height: 388.0,
                              child: GeneratedGroup33Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
