import 'package:flutter/material.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedPolygon3Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedEnteryourlocationWidget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup14Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedPolygon5Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup15Widget1.dart';
import 'package:flutterapp/toiletappapp/generatediphone14promax2widget1/generated/GeneratedGroup16Widget1.dart';

/* Frame iPhone 14 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(142, 230, 162, 255),
                              ),
                            ),
                            Positioned(
                              left: 217.89532470703125,
                              top: 689.0081787109375,
                              right: null,
                              bottom: null,
                              width: 37.89549255371094,
                              height: 37.89549255371094,
                              child: GeneratedPolygon3Widget1(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 631.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 63.0,
                              child: GeneratedGroup14Widget1(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 74.0081787109375,
                              child: GeneratedGroup6Widget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 124.0,
                              right: null,
                              bottom: null,
                              width: 391.0,
                              height: 785.0,
                              child: GeneratedGroup16Widget1(),
                            ),
                            Positioned(
                              left: 298.60870361328125,
                              top: 524.400146484375,
                              right: null,
                              bottom: null,
                              width: 37.89549255371094,
                              height: 37.89549255371094,
                              child: GeneratedPolygon5Widget1(),
                            ),
                            Positioned(
                              left: 272.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedGroup15Widget1(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 405.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 74.00820922851562,
                              child: GeneratedGroup13Widget1(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 74.00820922851562,
                              child: GeneratedGroup11Widget1(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 28.0,
                              right: null,
                              bottom: null,
                              width: 314.0,
                              height: 54.0,
                              child: GeneratedRectangle4Widget4(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 45.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 21.0,
                              child: GeneratedEnteryourlocationWidget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 54.0,
                              height: 53.0,
                              child: GeneratedGroup3Widget1(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 618.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 178.0,
                              child: GeneratedGroup36Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
