import 'package:flutter/material.dart';
import 'package:flutterapp/toiletappapp/generatedframe2widget/generated/Generated369metersWidget.dart';
import 'package:flutterapp/toiletappapp/generatedframe2widget/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/toiletappapp/generatedframe2widget/generated/GeneratedGroup36Widget3.dart';
import 'package:flutterapp/toiletappapp/generatedframe2widget/generated/GeneratedGroup37Widget3.dart';
import 'package:flutterapp/toiletappapp/generatedframe2widget/generated/GeneratedIPhone14ProMax2Widget2.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 932.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 430.0,
                    height: 932.0,
                    child: Stack(
                        clipBehavior: Clip.none,
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 430.0,
                            height: 932.0,
                            child: GeneratedIPhone14ProMax2Widget2(),
                          ),
                          Positioned(
                            left: 213.0,
                            top: 851.0,
                            right: null,
                            bottom: null,
                            width: 70.0,
                            height: 13.0,
                            child: Generated369metersWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.627906976744186;

                              final double height =
                                  constraints.maxHeight * 0.11532581312973612;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.3674418604651163,
                                    y: constraints.maxHeight *
                                        0.6534544981600389,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedGroup36Widget3(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 780.058837890625,
                            right: null,
                            bottom: null,
                            width: 76.0,
                            height: 37.3856201171875,
                            child: GeneratedGroup7Widget2(),
                          ),
                          Positioned(
                            left: 294.0,
                            top: 844.810546875,
                            right: null,
                            bottom: null,
                            width: 110.0,
                            height: 36.45098114013672,
                            child: GeneratedGroup37Widget3(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
